/*
SaladCloud API

Testing SystemLogsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package saladclient

import (
	"context"
	openapiclient "github.com/SaladTechnologies/salad-client"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_saladclient_SystemLogsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SystemLogsAPIService GetSystemLogs", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var organizationName string
		var projectName string
		var containerGroupName string

		resp, httpRes, err := apiClient.SystemLogsAPI.GetSystemLogs(context.Background(), organizationName, projectName, containerGroupName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
