/*
SaladCloud Public API

The SaladCloud Public API.

API version: 1.0.0-alpha.56
Contact: support@salad.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package salad-client

import (
	"encoding/json"
	"fmt"
)

// RestartRecipeDeploymentProblemType the model 'RestartRecipeDeploymentProblemType'
type RestartRecipeDeploymentProblemType string

// List of RestartRecipeDeploymentProblemType
const (
	NULL RestartRecipeDeploymentProblemType = "null"
)

// All allowed values of RestartRecipeDeploymentProblemType enum
var AllowedRestartRecipeDeploymentProblemTypeEnumValues = []RestartRecipeDeploymentProblemType{
	"null",
}

func (v *RestartRecipeDeploymentProblemType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := RestartRecipeDeploymentProblemType(value)
	for _, existing := range AllowedRestartRecipeDeploymentProblemTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid RestartRecipeDeploymentProblemType", value)
}

// NewRestartRecipeDeploymentProblemTypeFromValue returns a pointer to a valid RestartRecipeDeploymentProblemType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewRestartRecipeDeploymentProblemTypeFromValue(v string) (*RestartRecipeDeploymentProblemType, error) {
	ev := RestartRecipeDeploymentProblemType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for RestartRecipeDeploymentProblemType: valid values are %v", v, AllowedRestartRecipeDeploymentProblemTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v RestartRecipeDeploymentProblemType) IsValid() bool {
	for _, existing := range AllowedRestartRecipeDeploymentProblemTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to RestartRecipeDeploymentProblemType value
func (v RestartRecipeDeploymentProblemType) Ptr() *RestartRecipeDeploymentProblemType {
	return &v
}

type NullableRestartRecipeDeploymentProblemType struct {
	value *RestartRecipeDeploymentProblemType
	isSet bool
}

func (v NullableRestartRecipeDeploymentProblemType) Get() *RestartRecipeDeploymentProblemType {
	return v.value
}

func (v *NullableRestartRecipeDeploymentProblemType) Set(val *RestartRecipeDeploymentProblemType) {
	v.value = val
	v.isSet = true
}

func (v NullableRestartRecipeDeploymentProblemType) IsSet() bool {
	return v.isSet
}

func (v *NullableRestartRecipeDeploymentProblemType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRestartRecipeDeploymentProblemType(val *RestartRecipeDeploymentProblemType) *NullableRestartRecipeDeploymentProblemType {
	return &NullableRestartRecipeDeploymentProblemType{value: val, isSet: true}
}

func (v NullableRestartRecipeDeploymentProblemType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRestartRecipeDeploymentProblemType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

