/*
SaladCloud Public API

The SaladCloud Public API.

API version: 1.0.0-alpha.56
Contact: support@salad.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package saladclient

import (
	"encoding/json"
)

// checks if the CreateContainerRegistryAuthenticationAwsEcr type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateContainerRegistryAuthenticationAwsEcr{}

// CreateContainerRegistryAuthenticationAwsEcr struct for CreateContainerRegistryAuthenticationAwsEcr
type CreateContainerRegistryAuthenticationAwsEcr struct {
	AccessKeyId string `json:"access_key_id"`
	SecretAccessKey string `json:"secret_access_key"`
}

// NewCreateContainerRegistryAuthenticationAwsEcr instantiates a new CreateContainerRegistryAuthenticationAwsEcr object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateContainerRegistryAuthenticationAwsEcr(accessKeyId string, secretAccessKey string) *CreateContainerRegistryAuthenticationAwsEcr {
	this := CreateContainerRegistryAuthenticationAwsEcr{}
	this.AccessKeyId = accessKeyId
	this.SecretAccessKey = secretAccessKey
	return &this
}

// NewCreateContainerRegistryAuthenticationAwsEcrWithDefaults instantiates a new CreateContainerRegistryAuthenticationAwsEcr object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateContainerRegistryAuthenticationAwsEcrWithDefaults() *CreateContainerRegistryAuthenticationAwsEcr {
	this := CreateContainerRegistryAuthenticationAwsEcr{}
	return &this
}

// GetAccessKeyId returns the AccessKeyId field value
func (o *CreateContainerRegistryAuthenticationAwsEcr) GetAccessKeyId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessKeyId
}

// GetAccessKeyIdOk returns a tuple with the AccessKeyId field value
// and a boolean to check if the value has been set.
func (o *CreateContainerRegistryAuthenticationAwsEcr) GetAccessKeyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessKeyId, true
}

// SetAccessKeyId sets field value
func (o *CreateContainerRegistryAuthenticationAwsEcr) SetAccessKeyId(v string) {
	o.AccessKeyId = v
}

// GetSecretAccessKey returns the SecretAccessKey field value
func (o *CreateContainerRegistryAuthenticationAwsEcr) GetSecretAccessKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SecretAccessKey
}

// GetSecretAccessKeyOk returns a tuple with the SecretAccessKey field value
// and a boolean to check if the value has been set.
func (o *CreateContainerRegistryAuthenticationAwsEcr) GetSecretAccessKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SecretAccessKey, true
}

// SetSecretAccessKey sets field value
func (o *CreateContainerRegistryAuthenticationAwsEcr) SetSecretAccessKey(v string) {
	o.SecretAccessKey = v
}

func (o CreateContainerRegistryAuthenticationAwsEcr) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateContainerRegistryAuthenticationAwsEcr) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["access_key_id"] = o.AccessKeyId
	toSerialize["secret_access_key"] = o.SecretAccessKey
	return toSerialize, nil
}

type NullableCreateContainerRegistryAuthenticationAwsEcr struct {
	value *CreateContainerRegistryAuthenticationAwsEcr
	isSet bool
}

func (v NullableCreateContainerRegistryAuthenticationAwsEcr) Get() *CreateContainerRegistryAuthenticationAwsEcr {
	return v.value
}

func (v *NullableCreateContainerRegistryAuthenticationAwsEcr) Set(val *CreateContainerRegistryAuthenticationAwsEcr) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateContainerRegistryAuthenticationAwsEcr) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateContainerRegistryAuthenticationAwsEcr) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateContainerRegistryAuthenticationAwsEcr(val *CreateContainerRegistryAuthenticationAwsEcr) *NullableCreateContainerRegistryAuthenticationAwsEcr {
	return &NullableCreateContainerRegistryAuthenticationAwsEcr{value: val, isSet: true}
}

func (v NullableCreateContainerRegistryAuthenticationAwsEcr) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateContainerRegistryAuthenticationAwsEcr) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


