/*
SaladCloud API

The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.

API version: 0.9.0-alpha.13
Contact: cloud@salad.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package saladclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SystemLogList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SystemLogList{}

// SystemLogList Represents a list of system logs
type SystemLogList struct {
	// A list of system logs
	Items []SystemLog `json:"items"`
}

type _SystemLogList SystemLogList

// NewSystemLogList instantiates a new SystemLogList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemLogList(items []SystemLog) *SystemLogList {
	this := SystemLogList{}
	this.Items = items
	return &this
}

// NewSystemLogListWithDefaults instantiates a new SystemLogList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemLogListWithDefaults() *SystemLogList {
	this := SystemLogList{}
	return &this
}

// GetItems returns the Items field value
func (o *SystemLogList) GetItems() []SystemLog {
	if o == nil {
		var ret []SystemLog
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *SystemLogList) GetItemsOk() ([]SystemLog, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *SystemLogList) SetItems(v []SystemLog) {
	o.Items = v
}

func (o SystemLogList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SystemLogList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

func (o *SystemLogList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSystemLogList := _SystemLogList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSystemLogList)

	if err != nil {
		return err
	}

	*o = SystemLogList(varSystemLogList)

	return err
}

type NullableSystemLogList struct {
	value *SystemLogList
	isSet bool
}

func (v NullableSystemLogList) Get() *SystemLogList {
	return v.value
}

func (v *NullableSystemLogList) Set(val *SystemLogList) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemLogList) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemLogList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemLogList(val *SystemLogList) *NullableSystemLogList {
	return &NullableSystemLogList{value: val, isSet: true}
}

func (v NullableSystemLogList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemLogList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
