/*
SaladCloud API

The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.

API version: 0.9.0-alpha.13
Contact: cloud@salad.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package saladclient

import (
	"encoding/json"
	"fmt"
)

// checks if the ContainerLoggingDatadogTag type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContainerLoggingDatadogTag{}

// ContainerLoggingDatadogTag Represents a Datadog tag used for container logging metadata.
type ContainerLoggingDatadogTag struct {
	// The name of the metadata tag.
	Name string `json:"name" validate:"regexp=^.*$"`
	// The value of the metadata tag.
	Value                string `json:"value" validate:"regexp=^.*$"`
	AdditionalProperties map[string]interface{}
}

type _ContainerLoggingDatadogTag ContainerLoggingDatadogTag

// NewContainerLoggingDatadogTag instantiates a new ContainerLoggingDatadogTag object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContainerLoggingDatadogTag(name string, value string) *ContainerLoggingDatadogTag {
	this := ContainerLoggingDatadogTag{}
	this.Name = name
	this.Value = value
	return &this
}

// NewContainerLoggingDatadogTagWithDefaults instantiates a new ContainerLoggingDatadogTag object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContainerLoggingDatadogTagWithDefaults() *ContainerLoggingDatadogTag {
	this := ContainerLoggingDatadogTag{}
	return &this
}

// GetName returns the Name field value
func (o *ContainerLoggingDatadogTag) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ContainerLoggingDatadogTag) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ContainerLoggingDatadogTag) SetName(v string) {
	o.Name = v
}

// GetValue returns the Value field value
func (o *ContainerLoggingDatadogTag) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *ContainerLoggingDatadogTag) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *ContainerLoggingDatadogTag) SetValue(v string) {
	o.Value = v
}

func (o ContainerLoggingDatadogTag) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContainerLoggingDatadogTag) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["value"] = o.Value

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ContainerLoggingDatadogTag) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varContainerLoggingDatadogTag := _ContainerLoggingDatadogTag{}

	err = json.Unmarshal(data, &varContainerLoggingDatadogTag)

	if err != nil {
		return err
	}

	*o = ContainerLoggingDatadogTag(varContainerLoggingDatadogTag)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "value")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableContainerLoggingDatadogTag struct {
	value *ContainerLoggingDatadogTag
	isSet bool
}

func (v NullableContainerLoggingDatadogTag) Get() *ContainerLoggingDatadogTag {
	return v.value
}

func (v *NullableContainerLoggingDatadogTag) Set(val *ContainerLoggingDatadogTag) {
	v.value = val
	v.isSet = true
}

func (v NullableContainerLoggingDatadogTag) IsSet() bool {
	return v.isSet
}

func (v *NullableContainerLoggingDatadogTag) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContainerLoggingDatadogTag(val *ContainerLoggingDatadogTag) *NullableContainerLoggingDatadogTag {
	return &NullableContainerLoggingDatadogTag{value: val, isSet: true}
}

func (v NullableContainerLoggingDatadogTag) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContainerLoggingDatadogTag) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
