/*
SaladCloud API

The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.

API version: 0.9.0-alpha.13
Contact: cloud@salad.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package saladclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ContainerRegistryAuthenticationBasic type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContainerRegistryAuthenticationBasic{}

// ContainerRegistryAuthenticationBasic Basic username and password authentication for generic container registries
type ContainerRegistryAuthenticationBasic struct {
	// Username for registry authentication
	Username string `json:"username" validate:"regexp=^.*$"`
	// Password for registry authentication
	Password string `json:"password" validate:"regexp=^.*$"`
}

type _ContainerRegistryAuthenticationBasic ContainerRegistryAuthenticationBasic

// NewContainerRegistryAuthenticationBasic instantiates a new ContainerRegistryAuthenticationBasic object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContainerRegistryAuthenticationBasic(username string, password string) *ContainerRegistryAuthenticationBasic {
	this := ContainerRegistryAuthenticationBasic{}
	this.Username = username
	this.Password = password
	return &this
}

// NewContainerRegistryAuthenticationBasicWithDefaults instantiates a new ContainerRegistryAuthenticationBasic object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContainerRegistryAuthenticationBasicWithDefaults() *ContainerRegistryAuthenticationBasic {
	this := ContainerRegistryAuthenticationBasic{}
	return &this
}

// GetUsername returns the Username field value
func (o *ContainerRegistryAuthenticationBasic) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *ContainerRegistryAuthenticationBasic) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *ContainerRegistryAuthenticationBasic) SetUsername(v string) {
	o.Username = v
}

// GetPassword returns the Password field value
func (o *ContainerRegistryAuthenticationBasic) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *ContainerRegistryAuthenticationBasic) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *ContainerRegistryAuthenticationBasic) SetPassword(v string) {
	o.Password = v
}

func (o ContainerRegistryAuthenticationBasic) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContainerRegistryAuthenticationBasic) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["username"] = o.Username
	toSerialize["password"] = o.Password
	return toSerialize, nil
}

func (o *ContainerRegistryAuthenticationBasic) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"username",
		"password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varContainerRegistryAuthenticationBasic := _ContainerRegistryAuthenticationBasic{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varContainerRegistryAuthenticationBasic)

	if err != nil {
		return err
	}

	*o = ContainerRegistryAuthenticationBasic(varContainerRegistryAuthenticationBasic)

	return err
}

type NullableContainerRegistryAuthenticationBasic struct {
	value *ContainerRegistryAuthenticationBasic
	isSet bool
}

func (v NullableContainerRegistryAuthenticationBasic) Get() *ContainerRegistryAuthenticationBasic {
	return v.value
}

func (v *NullableContainerRegistryAuthenticationBasic) Set(val *ContainerRegistryAuthenticationBasic) {
	v.value = val
	v.isSet = true
}

func (v NullableContainerRegistryAuthenticationBasic) IsSet() bool {
	return v.isSet
}

func (v *NullableContainerRegistryAuthenticationBasic) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContainerRegistryAuthenticationBasic(val *ContainerRegistryAuthenticationBasic) *NullableContainerRegistryAuthenticationBasic {
	return &NullableContainerRegistryAuthenticationBasic{value: val, isSet: true}
}

func (v NullableContainerRegistryAuthenticationBasic) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContainerRegistryAuthenticationBasic) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
