/*
SaladCloud Public API

The SaladCloud Public API.

API version: 1.0.0-alpha.56
Contact: support@salad.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package saladclient

import (
	"encoding/json"
)

// checks if the CreateContainerRegistryAuthentication type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateContainerRegistryAuthentication{}

// CreateContainerRegistryAuthentication struct for CreateContainerRegistryAuthentication
type CreateContainerRegistryAuthentication struct {
	Basic NullableCreateContainerRegistryAuthenticationBasic `json:"basic,omitempty"`
	GcpGcr NullableCreateContainerRegistryAuthenticationGcpGcr `json:"gcp_gcr,omitempty"`
	AwsEcr NullableCreateContainerRegistryAuthenticationAwsEcr `json:"aws_ecr,omitempty"`
	DockerHub NullableCreateContainerRegistryAuthenticationDockerHub `json:"docker_hub,omitempty"`
}

// NewCreateContainerRegistryAuthentication instantiates a new CreateContainerRegistryAuthentication object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateContainerRegistryAuthentication() *CreateContainerRegistryAuthentication {
	this := CreateContainerRegistryAuthentication{}
	return &this
}

// NewCreateContainerRegistryAuthenticationWithDefaults instantiates a new CreateContainerRegistryAuthentication object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateContainerRegistryAuthenticationWithDefaults() *CreateContainerRegistryAuthentication {
	this := CreateContainerRegistryAuthentication{}
	return &this
}

// GetBasic returns the Basic field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateContainerRegistryAuthentication) GetBasic() CreateContainerRegistryAuthenticationBasic {
	if o == nil || IsNil(o.Basic.Get()) {
		var ret CreateContainerRegistryAuthenticationBasic
		return ret
	}
	return *o.Basic.Get()
}

// GetBasicOk returns a tuple with the Basic field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateContainerRegistryAuthentication) GetBasicOk() (*CreateContainerRegistryAuthenticationBasic, bool) {
	if o == nil {
		return nil, false
	}
	return o.Basic.Get(), o.Basic.IsSet()
}

// HasBasic returns a boolean if a field has been set.
func (o *CreateContainerRegistryAuthentication) HasBasic() bool {
	if o != nil && o.Basic.IsSet() {
		return true
	}

	return false
}

// SetBasic gets a reference to the given NullableCreateContainerRegistryAuthenticationBasic and assigns it to the Basic field.
func (o *CreateContainerRegistryAuthentication) SetBasic(v CreateContainerRegistryAuthenticationBasic) {
	o.Basic.Set(&v)
}
// SetBasicNil sets the value for Basic to be an explicit nil
func (o *CreateContainerRegistryAuthentication) SetBasicNil() {
	o.Basic.Set(nil)
}

// UnsetBasic ensures that no value is present for Basic, not even an explicit nil
func (o *CreateContainerRegistryAuthentication) UnsetBasic() {
	o.Basic.Unset()
}

// GetGcpGcr returns the GcpGcr field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateContainerRegistryAuthentication) GetGcpGcr() CreateContainerRegistryAuthenticationGcpGcr {
	if o == nil || IsNil(o.GcpGcr.Get()) {
		var ret CreateContainerRegistryAuthenticationGcpGcr
		return ret
	}
	return *o.GcpGcr.Get()
}

// GetGcpGcrOk returns a tuple with the GcpGcr field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateContainerRegistryAuthentication) GetGcpGcrOk() (*CreateContainerRegistryAuthenticationGcpGcr, bool) {
	if o == nil {
		return nil, false
	}
	return o.GcpGcr.Get(), o.GcpGcr.IsSet()
}

// HasGcpGcr returns a boolean if a field has been set.
func (o *CreateContainerRegistryAuthentication) HasGcpGcr() bool {
	if o != nil && o.GcpGcr.IsSet() {
		return true
	}

	return false
}

// SetGcpGcr gets a reference to the given NullableCreateContainerRegistryAuthenticationGcpGcr and assigns it to the GcpGcr field.
func (o *CreateContainerRegistryAuthentication) SetGcpGcr(v CreateContainerRegistryAuthenticationGcpGcr) {
	o.GcpGcr.Set(&v)
}
// SetGcpGcrNil sets the value for GcpGcr to be an explicit nil
func (o *CreateContainerRegistryAuthentication) SetGcpGcrNil() {
	o.GcpGcr.Set(nil)
}

// UnsetGcpGcr ensures that no value is present for GcpGcr, not even an explicit nil
func (o *CreateContainerRegistryAuthentication) UnsetGcpGcr() {
	o.GcpGcr.Unset()
}

// GetAwsEcr returns the AwsEcr field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateContainerRegistryAuthentication) GetAwsEcr() CreateContainerRegistryAuthenticationAwsEcr {
	if o == nil || IsNil(o.AwsEcr.Get()) {
		var ret CreateContainerRegistryAuthenticationAwsEcr
		return ret
	}
	return *o.AwsEcr.Get()
}

// GetAwsEcrOk returns a tuple with the AwsEcr field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateContainerRegistryAuthentication) GetAwsEcrOk() (*CreateContainerRegistryAuthenticationAwsEcr, bool) {
	if o == nil {
		return nil, false
	}
	return o.AwsEcr.Get(), o.AwsEcr.IsSet()
}

// HasAwsEcr returns a boolean if a field has been set.
func (o *CreateContainerRegistryAuthentication) HasAwsEcr() bool {
	if o != nil && o.AwsEcr.IsSet() {
		return true
	}

	return false
}

// SetAwsEcr gets a reference to the given NullableCreateContainerRegistryAuthenticationAwsEcr and assigns it to the AwsEcr field.
func (o *CreateContainerRegistryAuthentication) SetAwsEcr(v CreateContainerRegistryAuthenticationAwsEcr) {
	o.AwsEcr.Set(&v)
}
// SetAwsEcrNil sets the value for AwsEcr to be an explicit nil
func (o *CreateContainerRegistryAuthentication) SetAwsEcrNil() {
	o.AwsEcr.Set(nil)
}

// UnsetAwsEcr ensures that no value is present for AwsEcr, not even an explicit nil
func (o *CreateContainerRegistryAuthentication) UnsetAwsEcr() {
	o.AwsEcr.Unset()
}

// GetDockerHub returns the DockerHub field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateContainerRegistryAuthentication) GetDockerHub() CreateContainerRegistryAuthenticationDockerHub {
	if o == nil || IsNil(o.DockerHub.Get()) {
		var ret CreateContainerRegistryAuthenticationDockerHub
		return ret
	}
	return *o.DockerHub.Get()
}

// GetDockerHubOk returns a tuple with the DockerHub field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateContainerRegistryAuthentication) GetDockerHubOk() (*CreateContainerRegistryAuthenticationDockerHub, bool) {
	if o == nil {
		return nil, false
	}
	return o.DockerHub.Get(), o.DockerHub.IsSet()
}

// HasDockerHub returns a boolean if a field has been set.
func (o *CreateContainerRegistryAuthentication) HasDockerHub() bool {
	if o != nil && o.DockerHub.IsSet() {
		return true
	}

	return false
}

// SetDockerHub gets a reference to the given NullableCreateContainerRegistryAuthenticationDockerHub and assigns it to the DockerHub field.
func (o *CreateContainerRegistryAuthentication) SetDockerHub(v CreateContainerRegistryAuthenticationDockerHub) {
	o.DockerHub.Set(&v)
}
// SetDockerHubNil sets the value for DockerHub to be an explicit nil
func (o *CreateContainerRegistryAuthentication) SetDockerHubNil() {
	o.DockerHub.Set(nil)
}

// UnsetDockerHub ensures that no value is present for DockerHub, not even an explicit nil
func (o *CreateContainerRegistryAuthentication) UnsetDockerHub() {
	o.DockerHub.Unset()
}

func (o CreateContainerRegistryAuthentication) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateContainerRegistryAuthentication) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Basic.IsSet() {
		toSerialize["basic"] = o.Basic.Get()
	}
	if o.GcpGcr.IsSet() {
		toSerialize["gcp_gcr"] = o.GcpGcr.Get()
	}
	if o.AwsEcr.IsSet() {
		toSerialize["aws_ecr"] = o.AwsEcr.Get()
	}
	if o.DockerHub.IsSet() {
		toSerialize["docker_hub"] = o.DockerHub.Get()
	}
	return toSerialize, nil
}

type NullableCreateContainerRegistryAuthentication struct {
	value *CreateContainerRegistryAuthentication
	isSet bool
}

func (v NullableCreateContainerRegistryAuthentication) Get() *CreateContainerRegistryAuthentication {
	return v.value
}

func (v *NullableCreateContainerRegistryAuthentication) Set(val *CreateContainerRegistryAuthentication) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateContainerRegistryAuthentication) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateContainerRegistryAuthentication) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateContainerRegistryAuthentication(val *CreateContainerRegistryAuthentication) *NullableCreateContainerRegistryAuthentication {
	return &NullableCreateContainerRegistryAuthentication{value: val, isSet: true}
}

func (v NullableCreateContainerRegistryAuthentication) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateContainerRegistryAuthentication) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


