/*
SaladCloud API

The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.

API version: 0.9.0-alpha.5
Contact: cloud@salad.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package saladclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ContainerGroupsQuotas type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContainerGroupsQuotas{}

// ContainerGroupsQuotas struct for ContainerGroupsQuotas
type ContainerGroupsQuotas struct {
	MaxCreatedContainerGroups               int32  `json:"max_created_container_groups"`
	ContainerInstanceQuota                  int32  `json:"container_instance_quota"`
	MaxContainerGroupReallocationsPerMinute *int32 `json:"max_container_group_reallocations_per_minute,omitempty"`
	MaxContainerGroupRecreatesPerMinute     *int32 `json:"max_container_group_recreates_per_minute,omitempty"`
	MaxContainerGroupRestartsPerMinute      *int32 `json:"max_container_group_restarts_per_minute,omitempty"`
}

type _ContainerGroupsQuotas ContainerGroupsQuotas

// NewContainerGroupsQuotas instantiates a new ContainerGroupsQuotas object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContainerGroupsQuotas(maxCreatedContainerGroups int32, containerInstanceQuota int32) *ContainerGroupsQuotas {
	this := ContainerGroupsQuotas{}
	this.MaxCreatedContainerGroups = maxCreatedContainerGroups
	this.ContainerInstanceQuota = containerInstanceQuota
	var maxContainerGroupReallocationsPerMinute int32 = 10
	this.MaxContainerGroupReallocationsPerMinute = &maxContainerGroupReallocationsPerMinute
	var maxContainerGroupRecreatesPerMinute int32 = 10
	this.MaxContainerGroupRecreatesPerMinute = &maxContainerGroupRecreatesPerMinute
	var maxContainerGroupRestartsPerMinute int32 = 10
	this.MaxContainerGroupRestartsPerMinute = &maxContainerGroupRestartsPerMinute
	return &this
}

// NewContainerGroupsQuotasWithDefaults instantiates a new ContainerGroupsQuotas object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContainerGroupsQuotasWithDefaults() *ContainerGroupsQuotas {
	this := ContainerGroupsQuotas{}
	var maxContainerGroupReallocationsPerMinute int32 = 10
	this.MaxContainerGroupReallocationsPerMinute = &maxContainerGroupReallocationsPerMinute
	var maxContainerGroupRecreatesPerMinute int32 = 10
	this.MaxContainerGroupRecreatesPerMinute = &maxContainerGroupRecreatesPerMinute
	var maxContainerGroupRestartsPerMinute int32 = 10
	this.MaxContainerGroupRestartsPerMinute = &maxContainerGroupRestartsPerMinute
	return &this
}

// GetMaxCreatedContainerGroups returns the MaxCreatedContainerGroups field value
func (o *ContainerGroupsQuotas) GetMaxCreatedContainerGroups() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaxCreatedContainerGroups
}

// GetMaxCreatedContainerGroupsOk returns a tuple with the MaxCreatedContainerGroups field value
// and a boolean to check if the value has been set.
func (o *ContainerGroupsQuotas) GetMaxCreatedContainerGroupsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxCreatedContainerGroups, true
}

// SetMaxCreatedContainerGroups sets field value
func (o *ContainerGroupsQuotas) SetMaxCreatedContainerGroups(v int32) {
	o.MaxCreatedContainerGroups = v
}

// GetContainerInstanceQuota returns the ContainerInstanceQuota field value
func (o *ContainerGroupsQuotas) GetContainerInstanceQuota() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ContainerInstanceQuota
}

// GetContainerInstanceQuotaOk returns a tuple with the ContainerInstanceQuota field value
// and a boolean to check if the value has been set.
func (o *ContainerGroupsQuotas) GetContainerInstanceQuotaOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContainerInstanceQuota, true
}

// SetContainerInstanceQuota sets field value
func (o *ContainerGroupsQuotas) SetContainerInstanceQuota(v int32) {
	o.ContainerInstanceQuota = v
}

// GetMaxContainerGroupReallocationsPerMinute returns the MaxContainerGroupReallocationsPerMinute field value if set, zero value otherwise.
func (o *ContainerGroupsQuotas) GetMaxContainerGroupReallocationsPerMinute() int32 {
	if o == nil || IsNil(o.MaxContainerGroupReallocationsPerMinute) {
		var ret int32
		return ret
	}
	return *o.MaxContainerGroupReallocationsPerMinute
}

// GetMaxContainerGroupReallocationsPerMinuteOk returns a tuple with the MaxContainerGroupReallocationsPerMinute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContainerGroupsQuotas) GetMaxContainerGroupReallocationsPerMinuteOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxContainerGroupReallocationsPerMinute) {
		return nil, false
	}
	return o.MaxContainerGroupReallocationsPerMinute, true
}

// HasMaxContainerGroupReallocationsPerMinute returns a boolean if a field has been set.
func (o *ContainerGroupsQuotas) HasMaxContainerGroupReallocationsPerMinute() bool {
	if o != nil && !IsNil(o.MaxContainerGroupReallocationsPerMinute) {
		return true
	}

	return false
}

// SetMaxContainerGroupReallocationsPerMinute gets a reference to the given int32 and assigns it to the MaxContainerGroupReallocationsPerMinute field.
func (o *ContainerGroupsQuotas) SetMaxContainerGroupReallocationsPerMinute(v int32) {
	o.MaxContainerGroupReallocationsPerMinute = &v
}

// GetMaxContainerGroupRecreatesPerMinute returns the MaxContainerGroupRecreatesPerMinute field value if set, zero value otherwise.
func (o *ContainerGroupsQuotas) GetMaxContainerGroupRecreatesPerMinute() int32 {
	if o == nil || IsNil(o.MaxContainerGroupRecreatesPerMinute) {
		var ret int32
		return ret
	}
	return *o.MaxContainerGroupRecreatesPerMinute
}

// GetMaxContainerGroupRecreatesPerMinuteOk returns a tuple with the MaxContainerGroupRecreatesPerMinute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContainerGroupsQuotas) GetMaxContainerGroupRecreatesPerMinuteOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxContainerGroupRecreatesPerMinute) {
		return nil, false
	}
	return o.MaxContainerGroupRecreatesPerMinute, true
}

// HasMaxContainerGroupRecreatesPerMinute returns a boolean if a field has been set.
func (o *ContainerGroupsQuotas) HasMaxContainerGroupRecreatesPerMinute() bool {
	if o != nil && !IsNil(o.MaxContainerGroupRecreatesPerMinute) {
		return true
	}

	return false
}

// SetMaxContainerGroupRecreatesPerMinute gets a reference to the given int32 and assigns it to the MaxContainerGroupRecreatesPerMinute field.
func (o *ContainerGroupsQuotas) SetMaxContainerGroupRecreatesPerMinute(v int32) {
	o.MaxContainerGroupRecreatesPerMinute = &v
}

// GetMaxContainerGroupRestartsPerMinute returns the MaxContainerGroupRestartsPerMinute field value if set, zero value otherwise.
func (o *ContainerGroupsQuotas) GetMaxContainerGroupRestartsPerMinute() int32 {
	if o == nil || IsNil(o.MaxContainerGroupRestartsPerMinute) {
		var ret int32
		return ret
	}
	return *o.MaxContainerGroupRestartsPerMinute
}

// GetMaxContainerGroupRestartsPerMinuteOk returns a tuple with the MaxContainerGroupRestartsPerMinute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContainerGroupsQuotas) GetMaxContainerGroupRestartsPerMinuteOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxContainerGroupRestartsPerMinute) {
		return nil, false
	}
	return o.MaxContainerGroupRestartsPerMinute, true
}

// HasMaxContainerGroupRestartsPerMinute returns a boolean if a field has been set.
func (o *ContainerGroupsQuotas) HasMaxContainerGroupRestartsPerMinute() bool {
	if o != nil && !IsNil(o.MaxContainerGroupRestartsPerMinute) {
		return true
	}

	return false
}

// SetMaxContainerGroupRestartsPerMinute gets a reference to the given int32 and assigns it to the MaxContainerGroupRestartsPerMinute field.
func (o *ContainerGroupsQuotas) SetMaxContainerGroupRestartsPerMinute(v int32) {
	o.MaxContainerGroupRestartsPerMinute = &v
}

func (o ContainerGroupsQuotas) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContainerGroupsQuotas) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["max_created_container_groups"] = o.MaxCreatedContainerGroups
	toSerialize["container_instance_quota"] = o.ContainerInstanceQuota
	if !IsNil(o.MaxContainerGroupReallocationsPerMinute) {
		toSerialize["max_container_group_reallocations_per_minute"] = o.MaxContainerGroupReallocationsPerMinute
	}
	if !IsNil(o.MaxContainerGroupRecreatesPerMinute) {
		toSerialize["max_container_group_recreates_per_minute"] = o.MaxContainerGroupRecreatesPerMinute
	}
	if !IsNil(o.MaxContainerGroupRestartsPerMinute) {
		toSerialize["max_container_group_restarts_per_minute"] = o.MaxContainerGroupRestartsPerMinute
	}
	return toSerialize, nil
}

func (o *ContainerGroupsQuotas) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"max_created_container_groups",
		"container_instance_quota",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varContainerGroupsQuotas := _ContainerGroupsQuotas{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varContainerGroupsQuotas)

	if err != nil {
		return err
	}

	*o = ContainerGroupsQuotas(varContainerGroupsQuotas)

	return err
}

type NullableContainerGroupsQuotas struct {
	value *ContainerGroupsQuotas
	isSet bool
}

func (v NullableContainerGroupsQuotas) Get() *ContainerGroupsQuotas {
	return v.value
}

func (v *NullableContainerGroupsQuotas) Set(val *ContainerGroupsQuotas) {
	v.value = val
	v.isSet = true
}

func (v NullableContainerGroupsQuotas) IsSet() bool {
	return v.isSet
}

func (v *NullableContainerGroupsQuotas) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContainerGroupsQuotas(val *ContainerGroupsQuotas) *NullableContainerGroupsQuotas {
	return &NullableContainerGroupsQuotas{value: val, isSet: true}
}

func (v NullableContainerGroupsQuotas) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContainerGroupsQuotas) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
