/*
SaladCloud API

The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.

API version: 0.9.0-alpha.13
Contact: cloud@salad.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package saladclient

import (
	"encoding/json"
	"fmt"
)

// checks if the QueueJobCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueueJobCollection{}

// QueueJobCollection Represents a Queue Job Collection
type QueueJobCollection struct {
	// The list of queue jobs
	Items                []QueueJob `json:"items"`
	AdditionalProperties map[string]interface{}
}

type _QueueJobCollection QueueJobCollection

// NewQueueJobCollection instantiates a new QueueJobCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueueJobCollection(items []QueueJob) *QueueJobCollection {
	this := QueueJobCollection{}
	this.Items = items
	return &this
}

// NewQueueJobCollectionWithDefaults instantiates a new QueueJobCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueueJobCollectionWithDefaults() *QueueJobCollection {
	this := QueueJobCollection{}
	return &this
}

// GetItems returns the Items field value
func (o *QueueJobCollection) GetItems() []QueueJob {
	if o == nil {
		var ret []QueueJob
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *QueueJobCollection) GetItemsOk() ([]QueueJob, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *QueueJobCollection) SetItems(v []QueueJob) {
	o.Items = v
}

func (o QueueJobCollection) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueueJobCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *QueueJobCollection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQueueJobCollection := _QueueJobCollection{}

	err = json.Unmarshal(data, &varQueueJobCollection)

	if err != nil {
		return err
	}

	*o = QueueJobCollection(varQueueJobCollection)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "items")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableQueueJobCollection struct {
	value *QueueJobCollection
	isSet bool
}

func (v NullableQueueJobCollection) Get() *QueueJobCollection {
	return v.value
}

func (v *NullableQueueJobCollection) Set(val *QueueJobCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableQueueJobCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableQueueJobCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueueJobCollection(val *QueueJobCollection) *NullableQueueJobCollection {
	return &NullableQueueJobCollection{value: val, isSet: true}
}

func (v NullableQueueJobCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueueJobCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
