/*
SaladCloud API

The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.

API version: 0.9.0-alpha.5
Contact: cloud@salad.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package saladclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the WebhookSecretKey type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookSecretKey{}

// WebhookSecretKey Represents a webhook secret key
type WebhookSecretKey struct {
	// The webhook secret key
	SecretKey string `json:"secret_key"`
}

type _WebhookSecretKey WebhookSecretKey

// NewWebhookSecretKey instantiates a new WebhookSecretKey object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookSecretKey(secretKey string) *WebhookSecretKey {
	this := WebhookSecretKey{}
	this.SecretKey = secretKey
	return &this
}

// NewWebhookSecretKeyWithDefaults instantiates a new WebhookSecretKey object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookSecretKeyWithDefaults() *WebhookSecretKey {
	this := WebhookSecretKey{}
	return &this
}

// GetSecretKey returns the SecretKey field value
func (o *WebhookSecretKey) GetSecretKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SecretKey
}

// GetSecretKeyOk returns a tuple with the SecretKey field value
// and a boolean to check if the value has been set.
func (o *WebhookSecretKey) GetSecretKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SecretKey, true
}

// SetSecretKey sets field value
func (o *WebhookSecretKey) SetSecretKey(v string) {
	o.SecretKey = v
}

func (o WebhookSecretKey) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookSecretKey) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["secret_key"] = o.SecretKey
	return toSerialize, nil
}

func (o *WebhookSecretKey) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"secret_key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebhookSecretKey := _WebhookSecretKey{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWebhookSecretKey)

	if err != nil {
		return err
	}

	*o = WebhookSecretKey(varWebhookSecretKey)

	return err
}

type NullableWebhookSecretKey struct {
	value *WebhookSecretKey
	isSet bool
}

func (v NullableWebhookSecretKey) Get() *WebhookSecretKey {
	return v.value
}

func (v *NullableWebhookSecretKey) Set(val *WebhookSecretKey) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookSecretKey) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookSecretKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookSecretKey(val *WebhookSecretKey) *NullableWebhookSecretKey {
	return &NullableWebhookSecretKey{value: val, isSet: true}
}

func (v NullableWebhookSecretKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookSecretKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
